name: Deploy to AWS Elastic Beanstalk

on: [push]

concurrency:
  group: "eb"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [latest]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: npm test
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git'
      - name: Upload deployment package artifact
        uses: actions/upload-artifact@v3
        with:
          name: elastic-beanstalk
          path: deploy.zip

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: aws-elastic-beanstalk
      url: https://descent.live
    steps:
      - name: Download deployment package artifact
        uses: actions/download-artifact@v3
        with:
          name: elastic-beanstalk
      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          version_label: github-actions-${{ github.run_attempt }}
          deployment_package: deploy.zip
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ secrets.AWS_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_ENVIRONMENT_NAME }}
          region: ${{ secrets.AWS_REGION }}
